# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Create app on Developer portal and App connec"
  lane :create_app do
    create_app_online(
    username: "abduldiallo196@icloud.com",
    app_identifier: "com.abdulCo.Top-100-Albums",
    app_name: "Top100Albums",
    language: "English",
    app_version: "1.0.0",
    sku: "top100_fastlane"
)
  end

  desc "Sync sign in"
  lane :signing do
    sync_code_signing # match
  end

  desc "Build binary"
  lane :build do
    signing
  end

  desc "Release binary"
  lane :release do
    build
  end

end